### PR TITLE
KLC S4.6: add requirement for NC-pin-placement (on symbol box to prevent unwanted connections) + screenshot

### PR DESCRIPTION
**Pull request by jkriege2**
- added "The end of the pin should lie on the symbols outline box to prevent unwanted connections to the invisible pin (see screenshot below)." to S4.6
- added screenshot to S4.6

@SchrodingersGat  Could you have a look at this? Thanks!

### CODE REVIEW

**Comment by poeschlr** [comment]
Looks good to me.

**Comment by poeschlr** [comment]
One remark: please increase the KLC version and add your changes to the KLC history.

**Comment by jkriege2** [comment]
added to history .,. when this is merged, I will do the same for my other PR https://github.com/KiCad/kicad-website/pull/256

**Comment by nickoe** [comment]
On hold until SchrodingersGat acks this.

**Comment by poeschlr** [comment]
The main klc page also points to the current version number. So also edit that in `content/libraries/klc.adoc`

**Comment by jkriege2** [comment]
done!

**Comment by SchrodingersGat** [comment]
Looks good to me, thanks :

**Pull request merged**
