### PR TITLE
In F6.1, mention terminology used by stable version of KiCad.

### PR DESCRIPTION
**Pull request by ppelleti**
The text and screenshot for F6.1 use the terminology used by the nightlies.  I was very confused until I found [this thread](https://forum.kicad.info/t/where-do-i-set-footprint-placement-type/6477).

### CODE REVIEW

**Comment by poeschlr** [comment]
The same applies for rule 7.1.

Would you be so kind as to add this screenshot there as well?
The text should mention that through hole has been called normal in the 4.x release version.

**Comment by ppelleti** [comment]
Sure, I've added a screenshot of "Normal" to rule F7.1.

**Comment by poeschlr** [comment]
Looks good. It can be merged in my mind.

**Comment by SchrodingersGat** [comment]
Nice work :) first OSX screenshots!

**Pull request merged**
