### PR TITLE
Added cseduino v4 project made with kicad

### PR DESCRIPTION
**Pull request by jpralves**
The PCB for this project was created using kicad.

### CODE REVIEW

**Comment by marekr** [comment]
You put the closing quote for the website on a separate line.

**Comment by jpralves** [comment]
It's not compatible with Arduino Shields. Think of it has a learning project.

**Comment by marekr** [comment]
Ah, why close it? I wasn't agaisn't merging it.

**Comment by nickoe** [comment]
?

**Comment by jpralves** [comment]
Sorry. Wrong button.

**Comment by marekr** [comment]
@jpralves I didn't quite review it carefully before. I know the 3d preview is from KiCad of your board but your website doesn't showcase the 3d preview or even present any KiCad files, schematic, board or anything (zero mention). Are you going to add it?

**Comment by jpralves** [comment]
I'll update my page to point to the files.
The designs and all the kicad files are already published in the
https://github.com/jpralves/cseduino

Regards,

João


On Mon, Nov 2, 2015 at 9:49 PM, Marek Roszko <notifications@github.com>
wrote:

> @jpralves <https://github.com/jpralves> I didn't quite review it
> carefully before. I know the 3d preview is from KiCad of your board but
> your website doesn't showcase the 3d preview or even present any KiCad
> files, schematic, board or anything (zero mention). Are you going to add it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-website/pull/83#issuecomment-153168120>.
>



-- 
Joao Alves

**Pull request merged**
