### PR TITLE
RC clarification

### PR DESCRIPTION
**Pull request by adamwolf**
Hi folks!

Per the mailing list, I prepared a pull request to help clarify the RC situation on the download pages.  Feel free to change the wording--I am not 100% up to speed with the whole website like you folks probably are so I might have made some mistakes.

Thanks!

### CODE REVIEW

**Comment by marekr** [comment]
You need to rebase the branch you are on otherwise it'll pull in the massive merge commit.

**Comment by adamwolf** [comment]
Will do, sorry.

**Comment by adamwolf** [comment]
Looks better on my end.

**Comment by marekr** [comment]
"prerelease" should start with capital, otherwise should be fine

**Comment by adamwolf** [comment]
Changed, rebased, and pushed.

Thanks a bunch!

**Pull request merged**
