### PR TITLE
Adding install info for 4.0.0 on fedora.

### PR DESCRIPTION
**Pull request by reportingsjr**
I also changed the wording a touch on the fedora download page.

### CODE REVIEW

**Comment by reportingsjr** [comment]
I updated the wording of nightly dev build and old stable for all of the download pages that needed it.

**Comment by reportingsjr** [comment]
Vivid and Wily have 20141025 r4029.
Xenial has 4.0.0 rc1.

Not sure what to do with this then.

I added (Not recommended for new designs) to the pages that have old stable referenced. How do you want to handle ubuntu old stable info being incorrect? Accept this pull request and handle that in another? I think all of the pages need to be checked for old stable info.

**Comment by nickoe** [comment]
Ahh yeah, you are almost right. Xenial have the rc1, but wily don't have
any kicad it seems.

Just because we have made release the old stable is still called old
stable, in the lack of a real version number other than a bzr range, which
could be confusing to mention in many cases.

2015-12-15 1:04 GMT+01:00 Jon Neal <notifications@github.com>:

**Comment by reportingsjr** [comment]
Well, another question I have is.. do we provide version information for past releases of OSes at all?

Every OS/package management system seems to have chosen a different version to use. Many haven't had the actual "old stable" for quite a while and switched to an unstable version.

**Comment by nickoe** [comment]
I am sure that if some system is using a testing version between old stable and 4.0.1, the packager should just be poked and he will probably just update it to 4.0.1.  I don't see why we should not provide more information, to inform the user, if it makes sense.

**Comment by nickoe** [comment]
Thanks

**Pull request merged**
