### PR TITLE
Add SnapEDA interview blogpost link

### PR DESCRIPTION
**Pull request by nickoe**

### CODE REVIEW

**Comment by nickoe** [comment]
@stambaughw in case you missed this page.

**Comment by stambaughw** [comment]
@nickoe Did I forget to push this into master?  I thought I did.  Huh?

**Comment by nickoe** [comment]
@stambaughw  sorry for the ambigious mention, but I saw that you added a blog post about it, I added it to the in the media list.

**Comment by stambaughw** [comment]
I see said the blind man.  I'll get it right the next blog post.  Thanks.

**Pull request merged**
