### PR TITLE
KLC: update F9.1 to match current 5.2 terms and GUI

### PR DESCRIPTION
**Pull request by diegoherranz**
Raised at https://github.com/KiCad/kicad-website/issues/337

Thanks!

### CODE REVIEW

**Comment by diegoherranz** [comment]
By the way, I didn't push the KLC revision up because it doesn't really feel like anything has really changed.
But let me you if that needs to be updated.

**Comment by evanshultz** [comment]
@diegoherranz 
Can you please rev the two KLC files at https://github.com/KiCad/kicad-website/tree/master/content/libraries to make this PR bump the KLC version to 3.0.20?

**Comment by diegoherranz** [comment]
Rebased to master and updated the revision history.

Thanks!

**Comment by evanshultz** [comment]
@diegoherranz 
Thanks!

@nickoe 
Are you able to merge this?

**Comment by nickoe** [comment]
OK.

**Pull request merged**
