### PR TITLE
Grammar suggestions and tightening wording

### PR DESCRIPTION
**Pull request by sethhillbrand**
Additionally clarify file compatibility

### CODE REVIEW

**Comment by sethhillbrand** [comment]
Feel free to pick any/all/no aspects of this that are useful.

**Comment by nickoe** [comment]
The proposed changes look good to me. One think that I would like to write directly is the fact that with the new python3 support we also got the ability to use wx with gtk3, which has been an annoyance for packagers and users for quite some time. I am not sure how to word that in a nice way.

**Comment by nickoe** [comment]
WARNING: I will abuse this pull request to ask a question:

@poeschlr any gotchas, news or deprecations regarding the libraries that we need to mention?

**Comment by nickoe** [comment]
No objection for a couple of days, I guess we can merge this.

**Comment by poeschlr** [comment]
I did kind of miss the notification. But i can tell you that there is nothing truly significant that changed between v5.0.2 and 5.1. For the full dirty details see: https://github.com/KiCad/kicad-symbols/issues/1470 (or the changelog files attached to the symbol release on github.)

**Pull request merged**
