### PR TITLE
Added two more legal characters

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Comma
- Plus
- As per KLC

Matches PR for KLC - https://github.com/KiCad/kicad-library-utils/pull/167 - which is already merged

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Your trigger finger must have been itchy. Thanks @nickoe

**Comment by nickoe** [comment]
:)

**Comment by nickoe** [comment]
Just wondering; shouldn't this mandate an increment to the KLC version string?

**Comment by SchrodingersGat** [comment]
Uh, yes. Yes it should. I'll fix that.

**Pull request merged**
