### PR TITLE
Bumped KLC revision to 3.0.01

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- New characters allowed

Fixes https://github.com/KiCad/kicad-website/pull/227#issuecomment-342835957

### CODE REVIEW

**Comment by marekr** [comment]
Random leading zero?

**Comment by SchrodingersGat** [comment]
Not random. To differentiate between Vx.y.01 and Vx.y.10

**Comment by nickoe** [comment]
@SchrodingersGat Thank you, but I don't think that including leading zeros helps anyone. We don't do character by character numerical comparisons in the modern world anymore.

If you feel bored, read http://semver.org/#spec-item-2

**Comment by SchrodingersGat** [comment]
Done :)

**Pull request merged**
