### PR TITLE
Add CERN KiCad hackathon blog post.

### PR DESCRIPTION
**Pull request by stambaughw**
Would one of our esteemed website devs look over this pull request for the CERN KiCad hackathon.  My asciidoc knowledge is not the best and I would like an extra set of eyes to make sure I didn't make a mess of it.

Thanks,

Wayne

### CODE REVIEW

**Comment by stambaughw** [comment]
I inadvertently used the wrong urls in the links so I'll need to update them.  Does it make sense to close this pull request, make the changes and open another pull request or just merge this pull request, fix the broken links, and open another pull request.

**Comment by marekr** [comment]
You can just make the changes, commit it in git. Then do a rebase and squash the two commits together. Then force push it to your github branch which should update the PR.

**Comment by stambaughw** [comment]
I pushed the link fix so it should be good to go.  Do the posts get automatically added to the blog by date or do I need to edit some other asciidoc file so that it shows up in the blog post?

**Comment by nickoe** [comment]
@stambaughw Thank you for the update, it seems that it does not compile with asciidcotor as is, because of the i actute (í) in García. I fixed this with `conv -f latin1 -t utf-8`. I will commit it with my and close this.

**Comment by nickoe** [comment]
I squashed this and committed it in https://github.com/KiCad/kicad-website/commit/b7f2b553f4e511712bec5b7190d38a0cc653e7b4

**Comment by stambaughw** [comment]
Thanks Nick!  I'm not sure why the file was encoded latin1.  I actually copied an existing post file which should have been utf-8.  In the future I'll make sure the file is utf-8.

**Pull request closed without merging**
