### PR TITLE
Bulletted and wording improvement

### PR DESCRIPTION
**Pull request by ciampix**

### CODE REVIEW

**Comment by marekr** [comment]
You managed to commit the git diff >>>>>>>> ======= <<<<<<<< in the second commit.....

**Comment by ciampix** [comment]
Yes thanks, sorry for my lack of knowledge on git!

**Comment by marekr** [comment]
Try a git rebase to squash the commits and then force push. To eliminate the superflous commit.

**Comment by ciampix** [comment]
Done, see if I've done right this time, sorry...

**Comment by marekr** [comment]
That's fine, actually was more expecting of just squashing commits 2 and 3 together (since 3 was fixing 2) but its fine.

**Pull request merged**
