### PR TITLE
Update fedora nightly instalation instructions

### PR DESCRIPTION
**Pull request by jskorepa**
Point to updated copr

### CODE REVIEW

**Comment by svenstucki** [comment]
Was about to suggest the same, since the currently linked copr repository does not have a release for Fedora 25 (which is the current release since about 7 months). The official Fedora packages of KiCad don't have scripting enabled and this is a hassle free way to get it, so this is quite bad.

This PR definitely should've been merged a long time ago, together with the non controversial changes from #195.

**Comment by nickoe** [comment]
But is this thet way to remove the old copr?

**Comment by svenstucki** [comment]
Copr repos can be removed with `sudo dnf copr remove mangelajo/kicad` or one can just delete the file `/etc/yum.repos.d/_copr_<name>-<project>` (note the yum, this is correct for the path, but the `yum` tool is no longer used).

I wouldn't pollute the help page with that information though, since I think it's quite easy to figure out.

**Comment by marekr** [comment]
> I wouldn't pollute the help page with that information though, since I think it's quite easy to figure out.

With that kind of mindset, the age of the Linux desktop isn't going to happen


What happens when one swaps the two repos? Is the swap over clean?

**Comment by svenstucki** [comment]
I get where you're coming from but we're talking about nightly builds here.

**Comment by svenstucki** [comment]
I've just checked regarding the transition from one repo to the other. 

Going from Fedora official to either of those copr repos always works well, since both copr repos are using an epoch number of 100 to make sure their package is considered newer (official packages have no epoch set - it's considered as 0, the bigger number wins).

Unfortunately both copr repos use the same epoch and a different version naming scheme. E.g. the current official repo version string starts with `r10661` while the other starts with `6996`. Due to the way rpm compares those version strings (see [here](https://fedoraproject.org/wiki/Archive:Tools/RPM/VersionComparison)), the official repo will be considered older.

This is untested though, because as mentioned the unofficial copr repo does not have a release for Fedora 25.

To mitigate this there are several options:

- Reinstall `kicad` package (simplest)
- Drop the leading `r` from version in official copr repo
- Bump the epoch in official copr repo

**Comment by svenstucki** [comment]
@nickoe @marekr Please advise on what you think is the way to go, so we can get this or #195 merged as soon as possible.

I agree the situation regarding the nightly builds is sub optimal, but this mainly concerns advanced users. Meanwhile less experienced users might get confused by the outdated documentation.

**Comment by nickoe** [comment]
I have merged the changes manually.

**Pull request closed without merging**
