### PR TITLE
Source download

### PR DESCRIPTION
**Pull request by Thor-Arne**

### CODE REVIEW

**Comment by marekr** [comment]
Please rebase your pull request

**Comment by marekr** [comment]
You want to also add the TOML header (similar with the other download pages) with the correct icon (from /layouts/section/download.html) and removed the hardcoded source code link? Otherwise I'll merge anyway.

**Comment by Thor-Arne** [comment]
For now I just want it up so others can read through it and do necessary changes before the source download link is moved.
Main thing with this page is to have a sensible place to put the how-to-build pages.

**Comment by marekr** [comment]
Can't merge that file without the header. The download page generation fails.

**Comment by Thor-Arne** [comment]
Ok, thanks for letting me know. I didn't know that.
I'll have a go at the rest tomorrow, almost bedtime here now.

**Comment by nickoe** [comment]
There is still some issue. There is no two source entries and the top menu bar looks a bit odd. I am not sure why. Is this done or are you working on it still?

**Comment by Thor-Arne** [comment]
This page is intended to be linked to from download->source.
I added the header since marekr said it couldn't be merged without it.

I still think about the text on that page, not sure that I'm happy with it.
It would be nice to have it up there so others could comment on it.
Feel free to change anything.

**Comment by marekr** [comment]
Merged and then fixed links and the hardcoded download section.

**Pull request merged**
