### PR TITLE
Add screenshots for AppStream

### PR DESCRIPTION
**Pull request by lkundrak**
Add a set of screenshots that comply with AppStream requirements, for
various Linux application installers such as GNOME Software.

In particular, the screenshots are in 16:9 ratio, are in a resolution
that is sensible for in-app use and are taken on Linux without theme
customizations.

### CODE REVIEW

**Comment by stambaughw** [comment]
If for some reason these images are not acceptable for the home page, we could always create an separate page for appstream purposes.  Anyone else have any thoughts on this?

**Comment by lkundrak** [comment]
> If for some reason these images are not acceptable for the home page,

My thoughts were that the AppStream screenshots are only suitable for use within the app store apps; mainly because the sizing constraints make them look a bit awkward on the web.

> we could always create an separate page for appstream purposes. Anyone else have any thoughts on this?

Not sure what do you mean by "separate page for appstream purposes"?

Also, some context, I should've really linked to before (there's an older patch review linked to there that predates the Git migration): https://code.launchpad.net/~lkundrak/kicad/+git/kicad/+merge/323027

**Comment by marekr** [comment]
I see nothing wrong with the location they were put in.

**Comment by stambaughw** [comment]
On 4/24/2017 5:14 PM, Lubomir Rintel wrote:
>     If for some reason these images are not acceptable for the home page,
> 
> My thoughts were that the AppStream screenshots are only suitable for
> use within the app store apps; mainly because the sizing constraints
> make them look a bit awkward on the web.
> 
>     we could always create an separate page for appstream purposes.
>     Anyone else have any thoughts on this?
> 
> Not sure what do you mean by "separate page for appstream purposes"?

Just create a separate page on the website with the appstream images.
Does it even need to be linked anywhere?  You may have to change the
links in the appstream files but that shouldn't be too difficult.

**Comment by marekr** [comment]
Site did its update thing.

Images can be found at:

http://kicad-pcb.org/img/screenshots/appstream/


Probably better to link to those than using github links that you had in the patch.

**Comment by lkundrak** [comment]
Yes, thank you. Updated the patch.

**Comment by stambaughw** [comment]
Is there any reason why there isn't an image for gerbview?  I don't know
that there needs to be images for the calculator and the worksheet
editor but gerbview probably should be in there.

**Comment by stambaughw** [comment]
Do you mean you updated the KiCad source code patch?  If so, where is
the patch so I can get it merged?

**Pull request merged**
