### PR TITLE
Update macOS download with 5.0.2

### PR DESCRIPTION
**Pull request by adamwolf**

### CODE REVIEW

**Comment by adamwolf** [comment]
OK this should be good to go then.

**Comment by nickoe** [comment]
It looks like you removed the mirror link. 

Do we need to comment on why there are two installers? It is not clear to my why one is named 10_14 as well. I don't use macos, but I suspect that it is a macos release, but what does it mean? Maybe we need a comment to help the use choose the "best" choice for their platform?

**Comment by adamwolf** [comment]
Ah, ok, I see.

**Comment by adamwolf** [comment]
How's that?

**Comment by nickoe** [comment]
That looks good to me, I sort of missed it was partly explained in the nightly section. I think it is good to move to the top.

**Comment by nickoe** [comment]
Thank you!

**Pull request merged**
