### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by Caerbannog**
Lots of changes, see commit messages.
Please comment, I can cherry pick the controversial ones out.

Preview:
http://dallens.fr/about/

### CODE REVIEW

**Comment by cpavlina** [comment]
I don't understand your changes to the IRC page.

- What is the point of essentially swapping the two paragraphs?
- Why would you remove the explanation of the connection details? That's just going to scare beginners who'll think they need them.
- Why would you de-link "Freenode" in the table?
- Why would you rename "IRC" to "IRC Chat"? That's just wrong. It's Internet Relay Chat, not Internet Relay Chat Chat.

I'm going to be the grumpy guy complaining about people changing his work - but I really don't see a problem with that page as is. I quite dislike the new version.

**Comment by marekr** [comment]
The pages are now broken at 1024x768 resolution
http://i.imgur.com/kDpgWup.png

**Comment by Caerbannog** [comment]
@cpavlina The idea was for the webchat link to stand out (higher in the page, less clickable links). Anyway I will revert this, probably not such a great idea.

Nobody votes for "IRC Chat" in the menu, I take it?

@marekr Thanks, I had missed this page's layout.

**Comment by marekr** [comment]
Github complaining of merge conflict.

Also can you just reorder and squash the two IRC commits

**Pull request merged**
