### PR TITLE
Added Youtube link for FOSDEM video

### PR DESCRIPTION
**Pull request by bombledmonk**
It was inconvenient to watch this video so I added a link hosted on youtube and changed the verbiage slightly.

### CODE REVIEW

**Comment by marekr** [comment]
I am going to upload the video to the official KiCad youtube account so we can actually manage it but thanks for the suggestion.

**Comment by bombledmonk** [comment]
Sounds Great.

**Comment by nickoe** [comment]
@marekr   Just a suggestion. Maybe you should try to gain the audio level in the video a bit, it is very low, I have a hard time hearing it bumping my audio completely up.

**Comment by marekr** [comment]
I reencoded the mp4's audio by 23dB before uploading.

**Comment by nickoe** [comment]
Thank you.

**Pull request closed without merging**
