### PR TITLE
Master

### PR DESCRIPTION
**Pull request by easyw**
ECAD, MCAD screenshots and description for kicad stepup script

### CODE REVIEW

**Comment by marekr** [comment]
I really don't want to add a "feature" that is dependent on a script that's not even packaged with KiCad. If its the IDF export feature in general, sure, thats part of KiCad.

**Comment by easyw** [comment]
@marekr I really do not understand your comment...
you are talking of a "third party" script, when the script is open source and it is published at launchpad
http://bazaar.launchpad.net/~easyw/kicad-stepup/trunk/files
I'm a https://launchpad.net/~kicad-developers, just joined recently and I've done some already approved patches, plus this script...
In your point of view most of kicad's code comes from "third party" and shouldn't be considered...
may be you missed some recent conversation about the script @ developer's list...

**Comment by marekr** [comment]
"Third-party" is the origin because it has nothing to do with KiCad's main source code repository. It has nothing to do with being part of the developers mailing list group.

As Wayne said in those emails:
"Before we include the step up
script documentation in the KiCad documentation we need to include
script in KiCad."

until then its not a feature of KiCad but a "external tool".

**Comment by easyw** [comment]
as I told you, you're probably missing recent conversations:
As Wayne said recently:
https://lists.launchpad.net/kicad-developers/msg20210.html
"Maurice,
It's already mentioned here: http://kicad-pcb.org/help/external-tools/.
Is this what your looking for or did you have something else in mind?
I haven't had a chance to use this yet but it sounds really interesting
so it will be near the top of my list of things to include during the
next development cycle.
Thanks,
Wayne"
As Nick said recently:
https://lists.launchpad.net/kicad-developers/msg20245.html
"Hi Easyw
I think they will fit fine on the 3d-viewer page. But we would need to
be able to distinguish your kicad stepup script and the VRML only
models. I think it could be explained under the video with a few
sentences. Feel free to make a pull request with that and the images."
Moreover the images were already in the previous site:
http://confluence.kicad-pcb.org/display/KICAD/KiCad+EDA+Software+Suite
http://confluence.kicad-pcb.org/display/KICAD/KiCad+EDA+Software+Suite?preview=/589828/16973826/hackrf-one-stepup-kicad-3d-viewer.png
http://confluence.kicad-pcb.org/display/KICAD/KiCad+EDA+Software+Suite?preview=/589828/16973825/hackrf-one-stepup-catia-assembly.png

**Comment by nickoe** [comment]
@easyw Yes, I realize that I told to do as you did. But as an afterthought I have reconsidered the suggestion. It might indeed be inconsistent/confusing for people that we add the description to the 3D viewer page, because your script is not yet part of KiCad itself, but an external tool. Remember that the page is a page intended to only describe a KiCad features itself.

It might be better to just link the images on the external tools page, not really showing them on the page, since it is a bulleted list as of now. When people follow the link to source forge there is a description and images anywya.

**Comment by easyw** [comment]
@nickoe I consider a pitty not including the info to kicad users, at least in website, that the only option to export a realistic rendering of your project as a MCAD hierarchical assembly is through the script.
Then also the info in 3dviewer saying 
"Export a realistic rendering of your project as a picture or a MCAD hierarchical assembly." 
is confusing/not true...
@marekr when you say:
"Even then its a little dubious as you aren't using KiCad's functionality in the script (a python script at least uses KiCad's API), instead it's a FreeCAD script"
it shows me you haven't even read/understood what the script does; what you are asking it impossible through the kicad API (you should know if you know the kicad's API you are citing).
For your point of view kicad community should reject all VRML models coming from Wings3D, and build inside kicad itself a 3D modeler...

**Comment by easyw** [comment]
@nickoe 
to avoid confusing or giving false information on MCAD support to kicad users, please correct the 3dviewer page modifying the "MCAD hierarchical assembly" with "VRML hierarchical assembly"

**Pull request closed without merging**
