### PR TITLE
Added library info post

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds a blog post detailing the new additions to the website regarding official libraries.

It also describes the new kicad.github.io page

### CODE REVIEW

**Comment by nickoe** [comment]
I would like the blog posts to attempt to have a tighter coupling to the used title if it makes sense. In this case I would like the filename to be `kicad-offical-libraries.adoc`

**Comment by SchrodingersGat** [comment]
Thanks guys, I have made those two fixes now.

**Comment by marekr** [comment]
Your new commit...now creates a duplicate file

**Comment by SchrodingersGat** [comment]
Argh sorry about that. I duplicated the file but then edited the original.

**Pull request merged**
