### PR TITLE
Addedd VirtualSense to the Made with KiCad section

### PR DESCRIPTION
**Pull request by ciampix**

### CODE REVIEW

**Comment by marekr** [comment]
I can't access its web site? It appears down?

**Comment by ciampix** [comment]
no, it is up. Did you erroneously type www.virtualsense.it instead virtualsense.it?

**Comment by marekr** [comment]
It just seems its hosted on someones PC on a residential connection or something. Otherwise looks fine.

**Comment by ciampix** [comment]
You seem to have some connectivity problem. The site is hosted on a virtual machine on a private datacenter (https://www.seeweb.it/). Check for yourself...

**Comment by ciampix** [comment]
Sorry, I almost forgot, thanks!

**Comment by marekr** [comment]
Ah I found out why. Chrome itself is delaying the rendering. It is taking along time for it to download audio_trigger_montato_low.png (and probably display) since it is 1.5MB. Once it is cached its faster but caches are temporary.

http://i.imgur.com/KnQpPm4.png

**Pull request merged**
