### PR TITLE
Update Ubuntu download instruction for 5.1 release

### PR DESCRIPTION
**Pull request by jsreynaud**
Some modification for 5.1. I also added details to get easily a full install.

### CODE REVIEW

**Comment by marekr** [comment]
I guess we should wait until Friday when 5.1 is actually stable? Though you have "rc" builds right now for 5.1.

**Comment by jsreynaud** [comment]
Yes this is preparing work for future release by friday...

> I guess we should wait until Friday when 5.1 is actually stable? Though you have "rc" builds right now for 5.1.

Exactly. It's just a preparation for the release...

**Comment by marekr** [comment]
Yea but someone may want to install the RCs ;)

Any thoughts on combining the Ubuntu page with Linux Mint? Or we may be able to break out your PPA info as an include file for each page.

**Comment by jsreynaud** [comment]
Yes, for me Ubuntu and Mint info can be the same.

**Comment by nickoe** [comment]
Manually cherry-picked in https://github.com/KiCad/kicad-website/commit/5a28846a0d977b3a49d2d08895fa5758f4a2510d

**Pull request closed without merging**
