### PR TITLE
Update ubuntu.adoc

### PR DESCRIPTION
**Pull request by ciampix**
Updated Ubuntu download instructions based on user forum feedback.

### CODE REVIEW

**Comment by nickoe** [comment]
I guess this should also be repeated in the nightly section. Also, why to you terminate the bullets with semicolon?

**Comment by ciampix** [comment]
Because my elementary school teacher taught me to do so. But it is a general language rule, as I see it is reported in many "writer guides" in Italian, as these:
* http://comunicaresulweb.com/scrittura/elenchi-come-scrivere-elenco-puntato-numerato/
* http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/punteggiatura  ... see the list in the bottom (l'Accademia della Crusca is the reference for the Italian Language...)

**Comment by ciampix** [comment]
Corrected the nightly section for coherence though strangely it was almost right already.

**Comment by nickoe** [comment]
I pused a similar fix, thank you for highlighting the issue.

**Pull request closed without merging**
