### PR TITLE
KLC: extended S5.2 to explain pin-count in FPFilters

### PR DESCRIPTION
**Pull request by jkriege2**
- KLC S5.2: clarified the presence or not-presence of pin-count in FPFilters
- KLC S4.5: added link to S5.2

@SchrodingersGat Could you have a look? Thanks,
JAN

### CODE REVIEW

**Comment by poeschlr** [comment]
Looks good to me.

**Comment by jkriege2** [comment]
OK, version number increased and added history entry

@SchrodingersGat can this be merged?

**Comment by marekr** [comment]
Please rebase your branch onto master instead of merging in master so that merge commit isn't there.

**Comment by jkriege2** [comment]
better?

**Comment by marekr** [comment]
Yes. Now we wait for @SchrodingersGat

**Pull request merged**
