### PR TITLE
Blog note about Eagle import plugins

### PR DESCRIPTION
**Pull request by orsonmmz**

### CODE REVIEW

**Comment by marekr** [comment]
Its available in 4.0.7?

**Comment by nickoe** [comment]
The prefix "In development: " has also been used before, http://kicad-pcb.org/post/in-development-3d-plugins/

**Comment by orsonmmz** [comment]
Good point, I added an explicit information about availability, the note should be clearer now.

I did not want to make it sound like CERN did the job - I just wanted to stress the plugins have been developed with the donations money. I believe people sometimes wonder what happens with the money they gave us. Perhaps when they see their money is well spent, they may consider giving some more. Still, I agree credit should be given to the developers, therefore I mentioned their names in the note as well.

**Comment by marekr** [comment]
>I did not want to make it sound like CERN did the job

I figured, I wasn't trying to argue the line down at all. I just want to make sure we don't make someone who contributed possibly upset if they saw just CERN mentioned when they contributed a bunch of time too.

**Pull request merged**
