### PR TITLE
Sort all entries on Documentation alphabetical, adding links for available German documentation

### PR DESCRIPTION
**Pull request by tijuca**
I sorted all entries on the Documentation website in a alphabetical order as people will find the searched item easier. And finally adding the available German manuals.

### CODE REVIEW

**Comment by nickoe** [comment]
Ok, thanks.

**Comment by marekr** [comment]
FYI, I am kind of against putting Deutsch  above the English. 
English being the dominant and defacto project language should be at the top regardless of sorting.

**Comment by tijuca** [comment]
I was remembering all the other websites there translations available, those websites all use a strict alphabetical order. That's the reason for the sorting. But I can live with English on top for every tool too.

I was thinking about putting a flag before every language, like done in the settings for the KiCad tools. Or is this something you disagree? By doing this I can change the sorting again.

**Comment by nickoe** [comment]
I don't have a hard opinion on the sorting. But I don't think we shall use flags, flags are generally not good to denote a language, becuase there are many flags for english or french for example... Flags are used to denote a state or similar, not languages. If people have a hard time finding their languge in the list, they should try to use the features of their browser to search on the page.

**Comment by marekr** [comment]
Honestly I think the flags are silly given that a language doesn't necessarily match a single country like English or Spanish. And though we don't have translation for it but India has like 3 separate major languages, they would need the same flag then.

**Comment by tijuca** [comment]
O.k., I'll drop that idea.

**Pull request merged**
