### PR TITLE
Add --yes flag for add-apt-repository

### PR DESCRIPTION
**Pull request by Caerbannog**
So that no prompt happens during pasting the whole block.

### CODE REVIEW

**Comment by nickoe** [comment]
Are you sure this is better for the use to hide the choice prompt? I am not exactly sure about this.

**Comment by marekr** [comment]
Yea certainly don't want to cause package issues for users unexpectedly

**Comment by nickoe** [comment]
@marekr Could you try to clarify weather or not you oppose or accept this patch? It is not entirely clear from your commen... I think you oppose, but I am not sure.

**Comment by Caerbannog** [comment]
I understand that giving users a chance to change reconsider is good.
Although I think that the conformation prompt gives for sole information the name of the PPA, which is already in the command.
I just find confusing that, when pasting the whole block, the last commands will be taken as input to the prompt. They won't be executed and won't appear in the history.
Using "&&" instead of newlines would also work.

**Comment by marekr** [comment]
Thinking on it now, its probably ok to have the --yes, I mean the add-apt-repository should be pretty obvious whats going to happen with the --yes. @nickoe

**Comment by nickoe** [comment]
Yea, I agree. Lets try to include it and see if anyone ever cares to oppose :P

**Pull request merged**
