### PR TITLE
Changed OS X to MacOS.

### PR DESCRIPTION
**Pull request by adamwolf**
I swear I made this PR before--but maybe I forgot to submit it.  Let me know if you have any feedback.

### CODE REVIEW

**Comment by marekr** [comment]
What bothers me is "MacOS" is only really relevant for 10.12 and everything olderprobably still has OSX branding...

Calling is "Mac OS X" which is hilariously the pre "OSX" only branding may be more universal....

**Comment by adamwolf** [comment]
Do we want to include macOS on the download page, at least?

**Comment by marekr** [comment]
Lowercase the M in macOS per apple's own branding

**Comment by adamwolf** [comment]
Oh, Apple... (I'll update the PR shortly.)

**Comment by marekr** [comment]
@adamwolf Have a chance yet to rename it?

**Comment by adamwolf** [comment]
I was mostly afk, but I'll get to this tonight!

**Comment by nickoe** [comment]
Thank you. :)

**Pull request merged**
