### PR TITLE
improved description for KiCad StepUp tools

### PR DESCRIPTION
**Pull request by easyw**
following this forum thread
https://forum.kicad.info/t/trouble-with-3d-model-freecads-fault-or-kicads/15697/5
I decided to update StepUp tools description and to update the url to GH repo

### CODE REVIEW

**Comment by easyw** [comment]
@nickoe would you mind to review my PR?
Thanks
Maurice

**Comment by nickoe** [comment]
@easyw, thank you for the poke. But I think that we need to split it up in a paragraph or two, it looks like a long wall of text mentioning "random" stuff.

I would like to the see text slightly shorter and maybe only mentioning the most important features. We already link to the github page of your tool which have the README that will present the features in more detail.

Maybe make a paragraph after the first sentence, and then just mention some of the first points of the feature enumeration.

**Comment by easyw** [comment]
@nickoe 

> We already link to the github page of your tool which have the README that will present the features in more detail.

It is clear from the forum users that it is not really known that StepUp is the way to create 3D models for KiCAD as it is done for all the KiCAD 3D libraries...
I'm trying to improve this knowledge because even from the website link the description is very poor and a bit misleading ... 

> I would like to the see text slightly shorter and maybe only mentioning the most important features. 

I'm going to see what I can do to make a more concise but improved description.
Thx
M

**Comment by easyw** [comment]
@nickoe, 
now it should be short enough, but giving more info to users.

**Comment by nickoe** [comment]
@easyw Thank you. I have rebased your change locally and added some better formatting to the test. It should be live shortly.

**Comment by easyw** [comment]
@nickoe 
thanks a lot. It looks better now :smile:

**Pull request closed without merging**
