### PR TITLE
Update download.html

### PR DESCRIPTION
**Pull request by adamwolf**
Just some minor tweaks.  Feel free to reject.

### CODE REVIEW

**Comment by marekr** [comment]
"contactus" - should be specific, where? mailing list, pull request? etc

**Comment by adamwolf** [comment]
If there isn't already a "contact us" page, we need one.

**Comment by marekr** [comment]
Well that's a little debate.

What is the purpose of "contact us"? KiCad doesn't have a business entity like some other OSS projects do. So what is needed? We have the dev mailing list linked all over the contribute pages so thats not an issue there. Is media PR? Is it for general info? Is it to contact the website guys (which is just a pull request or an issue in most cases)?

**Comment by adamwolf** [comment]
The point of a contact page is so we can point people to it, so we don't
have to change every page when we change communication methods, and also so
we can be less verbose and not explain joining IRC or launchpad or a forum
or this or that every single time.

I spend too much time on KiCad already keeping the Mac builds current--I'm
just trying to help reduce the maintenance required on this website to make
it look up-to-date.

**Comment by marekr** [comment]
I'm just trying to envision what the content of the page would be. I see a rough picture in my head but it definitely wouldn't use the word "Us" because there is no central entity as "contact us" and the context of "us" is strange. 
The most valid thing I see is having a blurb saying any media, etc, etc kind of questions should be directed to Wayne. Otherwise it would just be a summary of existing info.

IRC is already under Community and it should be linked wherever IRC is mentioned. (Feel free to elaborate more on details of using IRC in that page but I also linked freenode webchat which makes it easier for people).

i.e.

Project Leader - Wayne - Annoy this guy with stuff that is related to media questions and stuff like that.
KiCad Dev List - Development questions/contributions/work (honestly should have a page clearly explaining it under Contribute)
KiCad User List - General kicad questions
KiCad Librarians List - Linked to in Contribute/Librarians
IRC - Read IRC page

I wouldn't link to say the other forums because it won't necessarily be "contact us" the developers at that point.

**Comment by nickoe** [comment]
In this specific use case I still think we should link this github repo somehow. By the contact is words the reader will have a hard time guessing who to address.

**Comment by adamwolf** [comment]
I think that works!

**Comment by marekr** [comment]
Did a separate commit to do the pull request tidbit.

**Pull request closed without merging**
